version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  checkout:
    executor: python/default
    working_directory: ~/project
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  build:
    executor: python/default
    working_directory: ~/project/server
    steps:
      - attach_workspace:
          at: ~/project
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .local
  test:
    executor: python/default
    working_directory: ~/project/server
    steps:
      - attach_workspace:
          at: ~/project
      - attach_workspace:
          at: ~/
      - run:
          command: pytest # ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - build
